#!/usr/bin/rxq/python
#coding=utf-8   
#python version:3.6 
#system:windows 10
import pdb
def missTime():
    # print("To Mr.Dog")
    print('\n'.join([''.join([('KaShing'[(x - y) % 7]
                              if ((x * 0.05) ** 2 + (y * 0.1) ** 2 - 1) ** 3 - (x * 0.05) ** 2 * (
                                                                                                 y * 0.1) ** 3 <= 0 else' ')
                             for x in range(-30, 30)]) for y in range(15, -15, -1)]))
    print("                                                  From Miss.Monkey")
    print("                                                  Apr 5th,2017")
